### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by itsbrex** [samdenty/git-icons#1]
Hey - purchased a license on Gumroad, but no matter which way I try to click it it just redirects to this repo.

**Comment by samdenty** [comment]
Hi there, you click on `Enter license` in the app. And you input the license key sent to you via email

**Comment by samdenty** [comment]
![CleanShot 2022-05-17 at 18 04 51@2x](https://user-images.githubusercontent.com/13242392/168870661-a55a2bb6-2692-41f1-8a67-ed2e8f15d9e6.png)
![CleanShot 2022-05-17 at 18 05 41@2x](https://user-images.githubusercontent.com/13242392/168870786-11036eab-a625-4bcd-85ef-2bc6d6a8a332.png)
<img width="529" alt="CleanShot 2022-05-17 at 18 06 07@2x" src="https://user-images.githubusercontent.com/13242392/168870790-fd3db6f0-2e83-40cf-9bd6-e1bcf5f4e98b.png">

**Comment by itsbrex** [comment]
Hmmm,. I didn't receive an email with a license key. I purchased another item from gumroad just now and receive a purchase email for that, but not for this for some reason.

**Comment by itsbrex** [comment]
@samdenty can I DM you somewhere?

**Comment by samdenty** [comment]
@itsbrex I've sent you the license key in a twitter DM. I don't think `brian@itsbrex.com` exists and thats why you didn't receive any emails
